<?php
namespace APDL;
define("APDL_SERVER_HOST", $_SERVER['HTTP_HOST']);
//TODO: SERVER IP
define("APDL_HTTP_REQUEST", $_SERVER['REQUEST_URI']);
define("APDL_HTTP_DOCROOT", $_SERVER['DOCUMENT_ROOT']);
define("APDL_INDEX_FILE", $_SERVER['SCRIPT_FILENAME']);
define("APDL_OUTPUT_SCREEN", 0);
define("APDL_OUTPUT_FILE", 1);
const OUTPUT_RETURN=0;
const OUTPUT_DIE=1;
const OUTPUT_DIE_CLEAN=2;
const L_FATAL = 1;
const L_ERROR = 2;
const L_WARNING = 3;
const L_INFO = 4;
const L_DUMP = 5;
const L_DEBUG = 6;
const SYSMODE_PRODUCTION=0;
const SYSMODE_DEBUG=1;
const SYSMODE_DEBUG_BACKTRACE=2;